services:
  myevents_postgres:
    image: postgres:15
    container_name: myevents_postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d eventsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data 

  myevents_api:
    build: .
    container_name: myevents_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=myevents_postgres;Port=5432;Database=eventsdb;Username=dev;Password=dev
      - JWT__Key=SuperSecretDevelopmentKey123456789
      - JWT__Issuer=MyEventsApi
      - JWT__Audience=MyEventsApiClient
    depends_on:
      myevents_postgres:
        condition: service_healthy

volumes:
  pgdata: